### ISSUE TITLE
switch template compiler to lodash to reduce dependency footprint

### ISSUE THREAD

**Issue by CNDW** [AppGeo/emberate#15]
lodash is much more universally used for node templating, and for most people would result in a smaller dependency footprint, especially considering that ember 2.0+ is using htmlbars and many people are not using handlebars.

**Comment by knownasilya** [comment]
Ember still uses handlebars (htmlbars is ontop of handlebars, they work together), plus this is server side only.

**Comment by CNDW** [comment]
handlebars is no longer an ember dependency. htmlbars is on top of handlebars, but ember packages it into the `ember-template-compiler.js` file with the rest of ember. Since it's server side, it would be nice to not have to include handlebars if it's not being explicitly used. 

At the very least we should update the dependency versions as the peer-dependency is on a very old version of handlebars

**Comment by knownasilya** [comment]
I would just update it. I think it makes sense to keep it, since people that use this library would already know how to use the templating language so they can create their own templates if need be.

**Comment by CNDW** [comment]
Yea, I was suggesting moving to .ejs format for the template to use lodash.template just because it's a more commonly used dependency. But I think that ember's htmlbars template compiler actually does have a peer dependency on handlebars, so I think you are right, I'll just update the version sometime in the near future.
