### ISSUE TITLE
es6 module support

### ISSUE THREAD

**Issue by CNDW** [AppGeo/emberate#16]
Ember currently supports es6 as a first class citizen, we should be using a require shim function to test for es6 format in the app.js template rather than basic requires

**Comment by knownasilya** [comment]
We could have a toggle to generate es6 syntax template instead.

**Comment by CNDW** [comment]
I don't think we need to generate the app module in es6 format. Modules that are exported using es6 have to be required using `require('module').default`, we can put a simple shim function in the template to check for that and automatically output the default export if the imported module is es6.
