### ISSUE TITLE
Ember's default resolver is incompatible with newer ember features

### ISSUE THREAD

**Issue by CNDW** [AppGeo/emberate#18]
The current implementation is using ember's default resolver by attaching the require statements to the application object using basic naming conventions. This works great for basic applications, but quickly falls apart when trying to do anything with add ons or namespaces. 

On the `use-loader` branch I have a working implementation that pulls in the [JJ Abrams resolver](https://github.com/ember-cli/ember-resolver) and the [loader.js](https://github.com/ember-cli/loader.js) used in ember-cli. The template then constructs an entry file that wraps the commonjs requires in an AMD implementation that is compatible with the one used by Ember and Ember-cli. This approach should make the tool more future proof, as we no longer have to 're-impliment' the module based features that are added to ember as they come up.

This is also a very large change on a philosophical level from how the utility currently works. I would love some feedback on how the branch could be improved, or what we could/should cut from the existing tool.

**Comment by knownasilya** [comment]
I'm assuming this would be a major bump for the tool.

What kind of features do you think would/should be cut?

**Comment by CNDW** [comment]
I don't think any features need to be cut, but both the `orderStream` and `inflectStream` steps are completely useless with this approach. Also the tests are completely broken, and without the ordering, would need to be changed to test module resolution rather than a static analysis of the output files. The biggest change, is for this to work, we have to transpile the ember-resolver into a vendor directory and package it together, meaning the resolver is in lock step with emberate. Also users overriding the default template could potentially break the tool completely, since it's now importing client side lib code from the emberate module.

**Comment by knownasilya** [comment]
> Also users overriding the default template could potentially break the tool completely, since it's now importing client side lib code from the emberate module.

Maybe we include a partial with the resolver code, which anyone overriding could include to make sure their custom template is intact?

Tests would need to be fixed before we release these changes. Other then that, it looks promising.
